const accountantNose =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiIHZpZXdCb3g9IjAgMCAxMDAgMjUiICBmaWxsPSJub25lIiBzdHJva2U9IiNjYWNhY2EiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIj48cGF0aCBkPSJNOTkgLjVINjljLTE3LjMzIDguMzMtMzAuNjcgMTYuNjctNDcgMjRtLTIxLjUgMGgyMSIvPjwvc3ZnPg==";

export default accountantNose;
